### ISSUE TITLE
new pharmacy table - abx intent

### ISSUE THREAD

**Issue by edward-data-sci** [LifebellAI/mimiciv-queries#2]
https://github.com/LifebellAI/mimiciv-queries/blob/097adc9b1768d4265a997a2e2093fe9f16102cfc/3_iv_antibiotics.sql#L18

As per discussion w/ Alistair, need another table that pulls data from pharmacy table not inputevents table, as it represents intent to administer abx

**Comment by edward-data-sci** [comment]
also included in here - epinephrine, dopamine, dobutamine

**Comment by rjaved111** [comment]
Going to pick this one up if that's okay !

**Comment by edward-data-sci** [comment]
sounds good - Mike wanted me to check with Adnan on the list of antibiotics, but that should only result in a small change in the final query, if any

**Comment by rjaved111** [comment]
Ah woops I forgot, you're right, I totally forgot thar this one won't be
possible without the list of specific antibiotics

I'll unassign myself! I just needed this for a labeling check I wanted to
do this week, but I can figure out a different way
